env:
  global:
    - DOCKER_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - DOCKER_BRANCH=${DOCKER_BRANCH//[\@\/]/-}
    - TESTS_TYPE=${TESTS_TYPE}
    - SMOKE_TESTS_TAG=@smoke_test
    - EXTENDED_TESTS_TAG=@extended_tests_part_1,@extended_tests_part_2
    - BRANCH_WITH_FULL_TESTS=master
    - APP_REPO=js-payments
    - APP_BRANCH=$DOCKER_BRANCH
    - DOCKER_TAG="docker-compose -f py-payments-testing/docker-compose.yml run"
    - RUN_TESTS="-e REMOTE=true tests poetry run behave features"
    - BUILD_NAME=${DOCKER_BRANCH}/$TRAVIS_BUILD_NUMBER
language: node_js
node_js:
  - 10
services:
  - docker
install: skip
before_script:
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  - if [[ ! $TRAVIS_BRANCH =~ ^release\/.*$ ]] && [[ "$TRAVIS_BRANCH" != "master" ]]; then git clone --branch=develop --depth=1 https://github.com/SecureTrading/py-payments-testing.git; fi
  - if [[ $TRAVIS_BRANCH =~ ^release\/.*$ ]] || [[ "$TRAVIS_BRANCH" == "master" ]]; then git clone --branch=master --single-branch --depth=1 https://github.com/SecureTrading/py-payments-testing.git; fi
  - docker-compose -f py-payments-testing/docker-compose.yml pull
  - docker-compose -f py-payments-testing/docker-compose.yml up -d
jobs:
  include:
    - stage: Unit tests & Docker build
      name: Unit tests
      before_script: skip
      script:
        - npm install
        - npm run coverage
        - npm run snyk
    - name: Build docker
      before_script: skip
      script:
        - docker build . --tag "securetrading1/js-payments:$DOCKER_BRANCH"
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push "securetrading1/js-payments:$DOCKER_BRANCH"
    - stage: Behavioral test - full set of tests
      name: 'Card payments common tests - chrome'
      script:
        - ${DOCKER_TAG} tests poetry run behave -i mock_
    - name: 'Visa Checkout tests - chrome'
      script:
        - ${DOCKER_TAG} tests poetry run behave -i visa_checkout_tests.feature
    - name: 'ApplePay tests part 1 - safari 12.1, OS X Mojave'
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Safari -e BROWSER_VERSION=12.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=apple_test_part1
    - name: 'ApplePay tests part 2 - safari 12.1, OS X Mojave'
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Safari -e BROWSER_VERSION=12.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=apple_test_part2
    - stage: BrowserStack - smoke tests
      name: "Behavioural test: firefox 73 Windows 10"
      if: branch=develop
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Firefox -e BROWSER_VERSION=73.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: IE 11, Windows 10"
      if: branch=develop
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=IE -e BROWSER_VERSION=11.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: iPhone 8, iOS 11.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="iPhone 8" -e OS_VERSION=11 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: chrome 83, Windows 8.1"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8.1 -e BROWSER=chrome -e BROWSER_VERSION=83.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: chrome 80, OS X Catalina"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="Catalina" -e BROWSER=chrome -e BROWSER_VERSION=80.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: firefox 73, Windows 8.1"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=8.1 -e BROWSER=Firefox -e BROWSER_VERSION=73.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: firefox 74, OS X Catalina"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="Catalina" -e BROWSER=Firefox -e BROWSER_VERSION=74.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    # - name: "Behavioural test: IE 10, Windows 10"
    #   if: branch=master
    #   script:
    #     - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=7 -e BROWSER=IE -e BROWSER_VERSION=10.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    # - name: "Behavioural test: edge 80, Windows 10"
    #   if: branch=master
    #   script:
    #     - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Edge -e BROWSER_VERSION=80.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: edge 18, Windows 10"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Edge -e BROWSER_VERSION=18.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: safari 11.1, OS X High Sierra"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION="High Sierra" -e BROWSER=Safari -e BROWSER_VERSION=11.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: iPhone XS, iOS 12.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="iPhone XS" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: iPad 7th, iOS 13.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="iPad 7th" -e OS_VERSION=13 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: Google Nexus 6, Android 6.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Google Nexus 6" -e OS_VERSION=6.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: Samsung Galaxy S8, Android 7.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S8" -e OS_VERSION=7.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: Samsung Galaxy S10 Plus, Android 9.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S10 Plus" -e OS_VERSION=9.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: Google Pixel 4, Android 10.0"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Google Pixel 4" -e OS_VERSION=10.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$SMOKE_TESTS_TAG
    - name: "Behavioural test: firefox 73, Windows 10 - extended tests"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=Firefox -e BROWSER_VERSION=73.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=$EXTENDED_TESTS_TAG
    # - name: "Behavioural test: iPhone XR, iOS 12.0, Full list of tests - part 1"
    #   if: branch=master
    #   script:
    #     - ${DOCKER_TAG} -e DEVICE="iPhone XR" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=full_test_part_1
    # - name: "Behavioural test: iPhone XR, iOS 12.0, Full list of tests - part 2"
    #   if: branch=master
    #   script:
    #     - ${DOCKER_TAG} -e DEVICE="iPhone XR" -e OS_VERSION=12 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=full_test_part_2
    - name: "Behavioural test: Samsung Galaxy S9, Android 8.0, extended tests - part 1"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S9" -e OS_VERSION=8.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_1
    - name: "Behavioural test: Samsung Galaxy S9, Android 8.0, extended tests - part 2"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e DEVICE="Samsung Galaxy S9" -e OS_VERSION=8.0 -e REAL_MOBILE=true -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_2
    - name: "Behavioural test: IE 11, Windows 10, extended tests - part 1"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=IE -e BROWSER_VERSION=11.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_1
    - name: "Behavioural test: IE 11, Windows 10, extended tests - part 2"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS=Windows -e OS_VERSION=10 -e BROWSER=IE -e BROWSER_VERSION=11.0 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_2
    - name: "Behavioural test: safari 12.1, OS X Mojave, extended tests - part 1"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Safari -e BROWSER_VERSION=12.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_1
    - name: "Behavioural test: safari 12.1, OS X Mojave, extended tests - part 2"
      if: branch=master
      script:
        - ${DOCKER_TAG} -e OS="OS X" -e OS_VERSION=Mojave -e BROWSER=Safari -e BROWSER_VERSION=12.1 -e BS_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BS_USERNAME=$BROWSERSTACK_USERNAME -e BS_LOCAL_IDENTIFIER=$BROWSERSTACK_LOCAL_IDENTIFIER -e BUILD_NAME=$BUILD_NAME ${RUN_TESTS} --tags=extended_tests_part_2
after_success:
  - cat ./coverage/lcov.info | coveralls
addons:
  browserstack:
    forcelocal: true
    username:
      secure: AH4sfHC+edBLzaGZo0UVn70c88/AKjFV7YGqQq6+8g96izDov25nB7rPaPuQHqnnARVoM7FSyc9XoHOA8Xm10oKxIBbtofw7Ydj+8czjNwa6k7nS0Rbpzl2JmhhgGXwFhXmvFXBxXiApXrhMYtE9Lo0rQGt9fXhWU7JkC2x04E3fPVAI+9oQ9V1SxIAZL+WSDyjPc1ZwQT8gwFM+XZaEy2J99LhNuFYQzeI6szmdtM0ZBLiqfeD2tixIXNUY+HAtTvUgZqwE9h+hon8Y/c574zzUf5ZxXzSaZbeU3+HW0rl75YaiP9lABOE4rrsY3rFd56IqXz5W46b63ZYAP8essu79Ph4xM9poJTpmU65domfCebMApdfgbIo7aSV7uOeNfKnrb5udbnqiZPGTuQSNJ+UJOjXJUfvNx/qBVFDsE7DqMChmZByRIUXVANaWDw70ixBij/vS5fpDiHpJ0gneizqosx09Vv10/cb9QDJ4FRDggQKZF3bS1V4q3vX1sodudTIuQVgfg95iR2uiQNnEdTPmvbM37FO6t8h8Vqxx4UqRIyf3jasVqsk79LU7F5/KYhvWW/KLN2lq65J2tKsTa/xBT856ah18cIGSMoie892tEsZxLbDy8KMUDyrbWNE4n11ButzifQISDziK7vQ7OwD3k6lJ24UFKBUoa/Oiim0=
    access_key:
      secure: TXgjJzYRpKcoBX6exipmXWj8TRToxGBQoQz0agRHczP9THyguyopST1XiPDdhcLIn7SMNDVORyP0D5EvMpchhvJ1unDpIULlNWjp63NsoYBGrryBXv307yn3NoQ+Tzh6U6GUG59bNfsqqLMOYapIqm6xxEqpcx1svA4Zjoz2rvcUK2gBof0UuL6s0rESB/4rQkwk0MQZDzm10O6wb6CWreFw/BMBTSKMvwVNfo5K+il+Ch1MWy2riWqYhyvGdu5Y/CG39WIUowa/y1HjcYNTwLlETr0nqqF9BnOjS05fabGIUnLBmf80mb6AEyrmNeVzQJlcJ4/lvI4f1RhrKvnDE70Ac6RFMoVcxOLLdSJIDoInFSH5xI5E/clGBYfP44LRDhRPXI4++8CPDp+MHG8trAOMIef3ySZGWoaHknNQ/G/Xhrsy7NLoBGnpz2c7CJoNjAPAIt2fm7y3Re+oo/hrhCh5/oya+kEKrrPI8qy9GpidCup5/QD/jKjkJijfusvC3ZEluaw+izAY+7RgLcaOifUqtVAx10JQIpZufWHJkHVqzmfGiLIWbyhNNJcrF+PcWIZSZelPb9uljO325M3bR7ViVmMPDuLojv0Z0cD/KWdqWW/uL7G7uzGSKgdTkuL7LqeaPOOQHZ07+v8Ii9GTZVee4+TRzucUISgNPvBVVJI=
  hosts:
    - webservices.securetrading.net
    - merchant.securetrading.net
    - thirdparty.example.com
