language: node_js
node_js:
- '10'
before_install:
- npm install -g npm@latest
install:
- npm install
before_script:
- greenkeeper-lockfile-update
jobs:
  include:
    # - stage: "Build"
    #   name: "Compile for distribution"
    #   script: npm run prod
    # - stage: "Test"
    #   name: "Unit tests"
    #   script: npm run coverage
    - stage: "Test"
      name: "Behavioural test"
      script:
        - npm run prod
        - git clone https://github.com/SecureTrading/js-payments-testing
        - cd js-payments-testing
        - git checkout feature/ST-82-automated-tests-framework
        - make test_chrome_68_w10
after_success:
- cat ./coverage/lcov.info | coveralls
after_script:
- greenkeeper-lockfile-upload
addons:
  browserstack:
    forcelocal: true
    username:
      secure: AH4sfHC+edBLzaGZo0UVn70c88/AKjFV7YGqQq6+8g96izDov25nB7rPaPuQHqnnARVoM7FSyc9XoHOA8Xm10oKxIBbtofw7Ydj+8czjNwa6k7nS0Rbpzl2JmhhgGXwFhXmvFXBxXiApXrhMYtE9Lo0rQGt9fXhWU7JkC2x04E3fPVAI+9oQ9V1SxIAZL+WSDyjPc1ZwQT8gwFM+XZaEy2J99LhNuFYQzeI6szmdtM0ZBLiqfeD2tixIXNUY+HAtTvUgZqwE9h+hon8Y/c574zzUf5ZxXzSaZbeU3+HW0rl75YaiP9lABOE4rrsY3rFd56IqXz5W46b63ZYAP8essu79Ph4xM9poJTpmU65domfCebMApdfgbIo7aSV7uOeNfKnrb5udbnqiZPGTuQSNJ+UJOjXJUfvNx/qBVFDsE7DqMChmZByRIUXVANaWDw70ixBij/vS5fpDiHpJ0gneizqosx09Vv10/cb9QDJ4FRDggQKZF3bS1V4q3vX1sodudTIuQVgfg95iR2uiQNnEdTPmvbM37FO6t8h8Vqxx4UqRIyf3jasVqsk79LU7F5/KYhvWW/KLN2lq65J2tKsTa/xBT856ah18cIGSMoie892tEsZxLbDy8KMUDyrbWNE4n11ButzifQISDziK7vQ7OwD3k6lJ24UFKBUoa/Oiim0=
    access_key:
      secure: TXgjJzYRpKcoBX6exipmXWj8TRToxGBQoQz0agRHczP9THyguyopST1XiPDdhcLIn7SMNDVORyP0D5EvMpchhvJ1unDpIULlNWjp63NsoYBGrryBXv307yn3NoQ+Tzh6U6GUG59bNfsqqLMOYapIqm6xxEqpcx1svA4Zjoz2rvcUK2gBof0UuL6s0rESB/4rQkwk0MQZDzm10O6wb6CWreFw/BMBTSKMvwVNfo5K+il+Ch1MWy2riWqYhyvGdu5Y/CG39WIUowa/y1HjcYNTwLlETr0nqqF9BnOjS05fabGIUnLBmf80mb6AEyrmNeVzQJlcJ4/lvI4f1RhrKvnDE70Ac6RFMoVcxOLLdSJIDoInFSH5xI5E/clGBYfP44LRDhRPXI4++8CPDp+MHG8trAOMIef3ySZGWoaHknNQ/G/Xhrsy7NLoBGnpz2c7CJoNjAPAIt2fm7y3Re+oo/hrhCh5/oya+kEKrrPI8qy9GpidCup5/QD/jKjkJijfusvC3ZEluaw+izAY+7RgLcaOifUqtVAx10JQIpZufWHJkHVqzmfGiLIWbyhNNJcrF+PcWIZSZelPb9uljO325M3bR7ViVmMPDuLojv0Z0cD/KWdqWW/uL7G7uzGSKgdTkuL7LqeaPOOQHZ07+v8Ii9GTZVee4+TRzucUISgNPvBVVJI=
env:
  global:
    - secure: RI1zmwknxmll4FdYrREaHPfbrxcbfd5DP/gu7jxVinozYnirMqAgM8WGPrcR/B5o5JjUM31AG+xaHfizMAeJ6GcnAKm94DZqI+BKlgC7ZzFcorR44G3vN7+EaCYdpiGLypmG94KuWY53LOHOnjLLxX4EFQ5RUDPq4L3xD3RDWBO1t2ZlcniGuxCeILaZ5BpPS1gU/HjCjNFWDEHvg0M5EInxvMSnZXStv6GhdOugZATLhwprKB78SrJlujVTxwbCPtjdK/r/RyGfNiF4DU+eYens10xpb1vnAhxHhpPxefvqozaCJozmJJNllfKblWQXgbEwy2CU7Xp1fqhtG/HaZ1xT/jXE1PNI44j8ZXpqa8iTFR/LqKuUy5S1/L7OOjwI0C7dG254G7Q+y4hz78BjoNAb91R3am9Oigu4UeM9xH60NTlvEVLFCWkz2W5YFVRMYRlIdS8Iodf35tjbnVO65xlNYE2xX8kEZgb1SpcVrxaHr6jPaIXEJkxOLR4yMlWbu5ehymOuf84ar2iYA2CuwRfzgKwc5iQnl6dOPseB7TtOBMHr/APnubz+hirNQ5qSpCkuM+e40d+KzWqmFTnf8fh4hFGz6Xs8RfJVwXATF/P8pMolGm0tolJ5eCdGIz7MwG5GoK5glRNyMfq/zkrW9Zcu6GfpSYpjrv3JQK8tk98=
    - secure: aqbg4abO41LTbOaJLag+qtPNEGG2Raw9UHzaKWqGES7AWL+Wcj53rbPCe69JRZt66NfK39N0z6lWbCYiLbzj7fwqLpSp9IsyajCfvnoCStJ/IffdPkd+GAmptEXvtsEy/VjfhRtTttxdrW7TQfEPLAoAz0RH4vAVp2Ovj9xFV4Ichx/8Rs/5Ex0O6IaqPf8V3sToVgNb/lFliHHFF16yxvptQDWJZnfPt6u9JRLRTuoXC7R2CP55N36uFsCa4JpUSWOgeScda5hrnsc+JoNBcjS9Z8jAmTQ/1ChMhOjdq+OzZucvwFrTacsgezvfcHF7SfmHY4DvtGVroh11EBCtxBtWpJM7xin/X4l2XRT5aAVsZ2c/gu0j+6mCG6ATJjfGvSP1GTW9BWkcV+TD3xNeJ5T+VY5x6Y4RpdsAO17A5yNynqWa1f2IqNXKnphbgmSpzef/9gYtuTSGKmi7XAKZ3MoTkWXkUqpZZHnY4GlDAevqCd2YYiYo7PnsSv8CFxDaZA4mx9Mj7ecC/ftej9wpnzdDkVcotTom6u24VO7JulVzY71OxeK+qWez4btwWGS3XiyBubvsiuuoYwG7teaKJQsgZE9QH8DuIXz9gGPr7H0UzdlyLg16Pt9BXJ+SLiemjQxEtB1ePFjCtY98dtOSYQhIx//kq/aL4l3aRF8ZslQ=
