export enum BypassCards {
  AMEX = 'AMEX',
  ASTROPAYCARD = 'ASTROPAYCARD',
  DINERS = 'DINERS',
  DISCOVER = 'DISCOVER',
  JCB = 'JCB',
  MASTERCARD = 'MASTERCARD',
  MAESTRO = 'MAESTRO',
  PIBA = 'PIBA',
  VISA = 'VISA'
}
