name: 3-local-chrome-full-scheduled

on:
  schedule:
    - cron: '*/10 * * * *'
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  behave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-actions-1 # TODO Change to run on develop and master following https://github.community/t5/GitHub-Actions/Scheduled-builds-of-non-default-branch/m-p/53587#M8883
      - run: make check-docker-file-exists
      - run: make run-behave-chrome
    env:
      BEHAVE_TAGS: "@full_test"
