export const StorageEvents = {
  GET_LOCAL_STORAGE_ITEM: 'GET_LOCAL_STORAGE_ITEM',
  GET_SESSION_STORAGE_ITEM: 'GET_SESSION_STORAGE_ITEM',
  SET_LOCAL_STORAGE_ITEM: 'SET_LOCAL_STORAGE_ITEM',
  SET_SESSION_STORAGE_ITEM: 'SET_SESSION_STORAGE_ITEM',
};
