name: behavioural tests

on: push # TODO change to be more dynamic as to what is run on push and pull etc
env:
  COMPOSE_COMMAND: docker-compose -f py-payments-testing/docker-compose.yml run tests poetry run behave features # TODO move to makefile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build-app-docker
  chrome-latest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make docker-compose-up
      - run: $COMPOSE_COMMAND --tags=@smoke_test

#  chrome-latest-full:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: actions/checkout@v2
#      - run: make docker-compose-py-payments-testing
#      - run: $COMPOSE_COMMAND --tags=@full_test

