name: behavioural tests

on: push # TODO change to be more dynamic as to what is run on push and pull etc
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: make build-app-docker
  chrome-latest:
    runs-on: ubuntu-latest
    #needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make docker-compose-up
      - run: make behave-chrome
    env:
      BEHAVE_TAGS=@smoke_test

  chrome-latest-full:
    runs-on: ubuntu-latest
    #needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make docker-compose-up
      - run: make behave-chrome
    env:
      BEHAVE_TAGS=@full_test

