name: behavioural tests

on:
  repository_dispatch:
    types: [run-behave-event]
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  chrome-latest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make run-behave-chrome
    env:
      BEHAVE_TAGS: "@smoke_test"

  #chrome-latest-full:
  #  runs-on: ubuntu-latest
  #  needs: [build]
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: make run-behave-chrome
  #  env:
  #    BEHAVE_TAGS: "@full_test"

  #bs-chrome-79-smoke:
  #  runs-on: ubuntu-latest
  #  needs: [build]
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: make run-behave-browserstack
  #  env:
  #    BEHAVE_TAGS: "@smoke_test"
  #    OS: Windows
  #    OS_VERSION: 8.1
  #    BROWSER: chrome
  #    BROWSER_VERSION: 79.0

  #bs-firefox-73-smoke:
  #  runs-on: ubuntu-latest
  #  needs: [build]
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: make run-behave-browserstack
  #  env:
  #    BEHAVE_TAGS: "@smoke_test"
  #    OS: Windows
  #    OS_VERSION: 10
  #    BROWSER: Firefox
  #    BROWSER_VERSION: 73.0
