name: bs-chrome-smoke

on: push # TODO change to be more dynamic as to what is run on push and pull etc
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

bs-chrome-smoke:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: make run-behave-browserstack
  env:
    BEHAVE_TAGS: "@smoke_test"
    OS: Windows
    OS_VERSION: 8.1
    BROWSER: chrome
    BROWSER_VERSION: 79.0
