name: 3-bs-iphone-smoke

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  behave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-docker-file-exists
      - run: make run-behave-browserstack-real-device
    env:
      BEHAVE_TAGS: "@smoke_test"
      DEVICE: "iPhone X"
      OS_VERSION: 10
