name: chrome-latest-smoke

on: push
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  chrome-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make run-behave-chrome
    env:
      BEHAVE_TAGS: "@smoke_test"
