name: chrome-latest-full

on: push # TODO change to be more dynamic as to what is run on push and pull etc
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  chrome-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make run-behave-chrome
    env:
      BEHAVE_TAGS: "@full_test"
