name: 3-local-chrome-full

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  chrome-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-docker-file-exists
      - run: make run-behave-chrome
    env:
      BEHAVE_TAGS: "@full_test"
