name: unittest

on:
  push:
    branches:
      - master
      - develop
  # TODO change to be more dynamic as to what is run on push and pull etc

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run coverage
