name: snyk

on:
  branches:
    - master
    - github-actions-1
  # TODO change to be done on a schedule and to run 1 job against master and one against develop

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run snyk
