name: 4-snyk

on:
  pull_request:
    branches:
      - master
      - develop
  # TODO change to be done on a schedule and to run 1 job against master and one against develop

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
